spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 385041
    url: jdbc:mysql://localhost:3306/mysql?useUnicode=true&characterEncoding=utf8
#  发送邮件的配置文件
#  mail:
#    host: smtp.qq.com
#    username: 1228589545@qq.com
#    password: noabandon520yy
#    default-encoding: utf-8
server:
  port: 8083
  thymeleaf:
      cache: false
